### ISSUE TITLE
missing component information in decorator and in the imports in client/src/app/app.module.ts

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-lab3_angular-spark#32]
There is a piece missing from your lab because we made a mistake. You need to add a few lines to `client/src/app/app.module.ts`. Somehow we managed to not import or include the `UserComponent` so you should add an import like:

import {UserComponent} from './users/user.component';

and add `UserComponent` to the list of things in the `declarations`
field in the `NgModule` decorator.

That should make things happier.

**Comment by NicMcPhee** [comment]
I'm not entirely sure what we want to do about this. The current code doesn't have these changes, but everything builds and runs because we never actually _use_ the `UserComponent` anywhere.

We could modify the `UserListComponent` so that it's a list of instances of `UserComponent`s, or we could add another view that uses `UserComponent` in some way. Or we could just remove all the `UserComponent` stuff.

Thoughts?

**Comment by NicMcPhee** [comment]
Actually, it looks like 5d6e00c63ec69cc9cb4ee5acd7bfa924d6d9ced1 fixes this. It's still weird, though, because `UserComponent` is _never_ used anywhere in the project; the only references to it are in `user.component.spec.ts`. Is there a reasonable way to incorporate this into the lab, or should we remove all the `UserComponent` stuff?
