### ISSUE TITLE
Include filtering of Users on server (rather than using only Angular filtering)

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab3_angular-spark#34]
The `User` filtering in the sample code is all done via Angular instead of by making calls to the server and having it do some of the work.

**Comment by kklamberty** [comment]
I updated the title since this issue didn't seem to have anything to do with stories requested by customer... 

There is some filtering of users by age that seems to be implemented for the server side of things, but it is not used. Filtering by age is actually done using angular. However, you can hack the API to search by age... not sure if that means we are closer than we would be if that server filtering wasn't there or if it's still really an angular thing. Help please.

**Comment by NicMcPhee** [comment]
Yeah, I don't remember where that unhelpful title came from, TBH.

I think the idea was that the server provides some potentially nice services (like the ability to filter by age), but our Angular example never *used* any of those services, and instead grabbed everything and filtered it on the Angular side. That doesn't scale to situations where you have zillions of items on the server side but you only need a few dozen; you don't want to eat bandwidth and phone CPU filtering out those few dozen when the server could have done that for you.

**Comment by kklamberty** [comment]
I totally get *why* we want to filter on the server. I was just confused about why we didn't use that in our example to show students how filtering on the server is different from filtering on the client. I think we've made it extra confusing by implementing age filtering for the server and then not using it. I think we need an example of filtering on the server along with some comments about filtering on the server and some tests to check that (to model what it should look like and how to test it).
